version: 2

sources:
  - name: northwind
    database: curso-etl-101 
    schema: erp_northwind
    tables:
      - name: orders
      - name: customers
      - name: order_details
      - name: products
      - name: categories
      - name: employees
      - name: shippers
      - name: suppliers
      - name: territories
