version: 2

sources:
  - name: northwind
    description: Data from Northwind ERP
    database: curso-etl-101 
    schema: erp_northwind
    tables:
      - name: orders
        description: This table lists the orders from ERP Northwind
        columns:
          - name: order_id
            description: The primary key of table
      - name: customers
      - name: order_details
      - name: products
      - name: categories
      - name: employees
      - name: shippers
      - name: suppliers
      - name: territories
      - name: region